# Generated by Django 3.1.12 on 2025-02-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpMgmt', '0002_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='test@gmail.com', max_length=254, null=True, unique=True),
        ),
    ]
