# Generated by Django 5.1.6 on 2025-02-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpMgmt', '0003_auto_20250209_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Email',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
