# Generated by Django 5.1.6 on 2025-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpMgmt', '0004_remove_employee_email_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Role',
            field=models.CharField(choices=[('AD', 'EM')], default='employee', max_length=2),
        ),
    ]
