# Generated by Django 5.1.6 on 2025-02-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpMgmt', '0005_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Role',
            field=models.CharField(max_length=10),
        ),
    ]
