# Generated by Django 5.1.6 on 2025-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpMgmt', '0006_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Role',
            field=models.CharField(choices=[('AD', 'Admin'), ('EM', 'Employee')], max_length=2),
        ),
    ]
