# Generated by Django 5.1.6 on 2025-02-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpMgmt', '0008_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Desg',
            new_name='desg',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Role',
            new_name='role',
        ),
    ]
